---
title: "Pruebas ggplot"
author: "Diego Polo"
date: "12 de enero de 2018"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("./FuncionMultiplot.R")
library(ggplot2)
```

```{r}
datos=data.frame(muestra=seq(1,10000,1),x=runif(10000,-0.1,0.1),y=runif(10000,-0.1,0.1),z=runif(10000,0.9,1.1))

p1 <- ggplot(datos, aes(x=muestra, y=x)) +
    geom_line() +scale_y_continuous(limits=c(-0.2,0.2))+ scale_x_continuous(limits = c(500,1000))+ ggtitle("Eje x")+geom_hline(yintercept=mean(datos$x),color="red")+legend()

# Second plot
p2 <- ggplot(datos, aes(x=muestra, y=y)) +
    geom_line() + scale_y_continuous(limits=c(-0.2,0.2))+ scale_x_continuous(limits = c(500,1000))+ggtitle("Eje x")

# Third plot
p3 <- ggplot(datos, aes(x=muestra, y=z)) +
    geom_line() + scale_y_continuous(limits=c(0.7,1.2))+scale_x_continuous(limits = c(500,600))+ggtitle("Eje x")

# Fourth plot
p4 <- ggplot(subset(ChickWeight, Time==21), aes(x=weight, fill=Diet)) +
    geom_histogram(colour="black", binwidth=50) +
    facet_grid(Diet ~ .) +
    ggtitle("Final weight, by diet") +
    theme(legend.position="none")        # No legend (redundant in this graph)    
multiplot(p1,p2,p3,p4, layout=matrix(c(1,2,3,4,4,4,4,4,4,4,4,4), nrow=4, byrow=TRUE))
```

